name: meditrack_app
description: "A new Flutter project."
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  


  # Added packages for backend integration
  http: ^1.1.0
  flutter_secure_storage: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/heart_pulse.png

  # Fonts section (optional)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
